set -g prefix C-a

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g mode-keys vi
set-option -g renumber-windows on

# Make vim colors work properly, seems to only be necessary in alacritty
# but also does not appear to hurt ghostty.
set -g default-terminal "tmux-256color"

# Enable undercurl and color.
set -ga terminal-features ",*:usstyle"

# Support RGB color with SGR escape sequences.
set -gs terminal-overrides ",*:RGB"

# Turn on hyperlink support
set -ga terminal-features "*:hyperlinks"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'mrjones2014/smart-splits.nvim'

# Optional configurations with their default values if omitted:

set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)

set -g @smart-splits_move_left_key  'C-h' # key-mapping for navigation.
set -g @smart-splits_move_down_key  'C-j' #  --"--
set -g @smart-splits_move_up_key    'C-k' #  --"--
set -g @smart-splits_move_right_key 'C-l' #  --"--

set -g @smart-splits_resize_left_key  'M-h' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'M-j' #  --"--
set -g @smart-splits_resize_up_key    'M-k' #  --"--
set -g @smart-splits_resize_right_key 'M-l' #  --"--

set -g @nova-rows 0
set -g @nova-nerdfonts false

set -g @nova-pane "#I #W"

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#e0af68]#[bg=#1f2335]#[fg=#1f2335]#[bg=#e0af68]"
set -g @prefix_highlight_output_suffix ""

# Colors from tokyonight-storm
base_bg="#24283b"
active_bg="#414868"
active_fg="#7dcfff"
base_fg="#7aa2f7"

pane_separator="$active_bg"
pane_separator_active="#8db0ff"

set -g message-style "fg=$active_fg,bg=$active_bg"
set -g message-command-style "fg=$active_fg,bg=$active_bg"

set -gw window-status-current-style bold
set -g "@nova-status-style-bg" "$base_bg"
set -g "@nova-status-style-fg" "$base_fg"
set -g "@nova-status-style-active-bg" "$base_bg"
set -g "@nova-status-style-active-fg" "$active_fg"

set -g @nova-segment-prefix "#{?client_prefix,PREFIX,}"
set -g @nova-segment-prefix-colors "$base_bg"

set -g @nova-segment-session "(⌐■_■)"
set -g @nova-segment-session-colors "$active_fg"

set -g @nova-segments-0-left "session"
set -g @nova-pane-active-border-style "$pane_separator_active"
set -g @nova-pane-border-style "$pane_separator"

# Mirror the sesssion + window name to the terminal window title
set-option -g set-titles on
set-option -g set-titles-string "(⌐■_■) / #W"

# Open new windows and splits in the CWD
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Set the pane name to the cwd
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#(basename "#{pane_current_path}")'

# On new session: open vim and create a split below
set-hook -g session-created 'send-keys nvim Enter; split-window -h -c "#{pane_current_path}"; resize-pane -x 40%; select-pane -t 1'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
